// Code generated by protoc-gen-go. DO NOT EDIT.
// source: register.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetMinerReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMinerReq) Reset()         { *m = GetMinerReq{} }
func (m *GetMinerReq) String() string { return proto.CompactTextString(m) }
func (*GetMinerReq) ProtoMessage()    {}
func (*GetMinerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1303fe8288f4efb6, []int{0}
}

func (m *GetMinerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMinerReq.Unmarshal(m, b)
}
func (m *GetMinerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMinerReq.Marshal(b, m, deterministic)
}
func (m *GetMinerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMinerReq.Merge(m, src)
}
func (m *GetMinerReq) XXX_Size() int {
	return xxx_messageInfo_GetMinerReq.Size(m)
}
func (m *GetMinerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMinerReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMinerReq proto.InternalMessageInfo

type GetMinerRes struct {
	Miner                string   `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMinerRes) Reset()         { *m = GetMinerRes{} }
func (m *GetMinerRes) String() string { return proto.CompactTextString(m) }
func (*GetMinerRes) ProtoMessage()    {}
func (*GetMinerRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1303fe8288f4efb6, []int{1}
}

func (m *GetMinerRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMinerRes.Unmarshal(m, b)
}
func (m *GetMinerRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMinerRes.Marshal(b, m, deterministic)
}
func (m *GetMinerRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMinerRes.Merge(m, src)
}
func (m *GetMinerRes) XXX_Size() int {
	return xxx_messageInfo_GetMinerRes.Size(m)
}
func (m *GetMinerRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMinerRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetMinerRes proto.InternalMessageInfo

func (m *GetMinerRes) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMinerReq)(nil), "proto.GetMinerReq")
	proto.RegisterType((*GetMinerRes)(nil), "proto.GetMinerRes")
}

func init() { proto.RegisterFile("register.proto", fileDescriptor_1303fe8288f4efb6) }

var fileDescriptor_1303fe8288f4efb6 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xcf,
	0x2c, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xbc,
	0x5c, 0xdc, 0xee, 0xa9, 0x25, 0xbe, 0x99, 0x79, 0xa9, 0x45, 0x41, 0xa9, 0x85, 0x4a, 0xca, 0xc8,
	0xdc, 0x62, 0x21, 0x11, 0x2e, 0xd6, 0x5c, 0x10, 0x5b, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08,
	0xc2, 0x31, 0x72, 0xe7, 0xe2, 0x0f, 0x82, 0x1a, 0x16, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a,
	0x64, 0xc2, 0xc5, 0x01, 0xd3, 0x27, 0x24, 0x04, 0xb1, 0x41, 0x0f, 0xc9, 0x5c, 0x29, 0x4c, 0xb1,
	0x62, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xa0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x18, 0xb4, 0x78,
	0x5d, 0x9c, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegisterServiceClient is the client API for RegisterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegisterServiceClient interface {
	// get miner from the main node
	GetMiner(ctx context.Context, in *GetMinerReq, opts ...grpc.CallOption) (*GetMinerRes, error)
}

type registerServiceClient struct {
	cc *grpc.ClientConn
}

func NewRegisterServiceClient(cc *grpc.ClientConn) RegisterServiceClient {
	return &registerServiceClient{cc}
}

func (c *registerServiceClient) GetMiner(ctx context.Context, in *GetMinerReq, opts ...grpc.CallOption) (*GetMinerRes, error) {
	out := new(GetMinerRes)
	err := c.cc.Invoke(ctx, "/proto.RegisterService/GetMiner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServiceServer is the server API for RegisterService service.
type RegisterServiceServer interface {
	// get miner from the main node
	GetMiner(context.Context, *GetMinerReq) (*GetMinerRes, error)
}

// UnimplementedRegisterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRegisterServiceServer struct {
}

func (*UnimplementedRegisterServiceServer) GetMiner(ctx context.Context, req *GetMinerReq) (*GetMinerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMiner not implemented")
}

func RegisterRegisterServiceServer(s *grpc.Server, srv RegisterServiceServer) {
	s.RegisterService(&_RegisterService_serviceDesc, srv)
}

func _RegisterService_GetMiner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMinerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServiceServer).GetMiner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegisterService/GetMiner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServiceServer).GetMiner(ctx, req.(*GetMinerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegisterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RegisterService",
	HandlerType: (*RegisterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMiner",
			Handler:    _RegisterService_GetMiner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "register.proto",
}
