// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fcrpc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProofReq struct {
	Title                string         `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	AddPieceReq          []*AddpieceReq `protobuf:"bytes,2,rep,name=AddPieceReq,proto3" json:"AddPieceReq,omitempty"`
	AddPieceRes          []*AddpieceRes `protobuf:"bytes,3,rep,name=AddPieceRes,proto3" json:"AddPieceRes,omitempty"`
	PostReq              []*PostReq     `protobuf:"bytes,4,rep,name=PostReq,proto3" json:"PostReq,omitempty"`
	PostRes              []*PostRes     `protobuf:"bytes,5,rep,name=PostRes,proto3" json:"PostRes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProofReq) Reset()         { *m = ProofReq{} }
func (m *ProofReq) String() string { return proto.CompactTextString(m) }
func (*ProofReq) ProtoMessage()    {}
func (*ProofReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_724d63c0ba825e88, []int{0}
}

func (m *ProofReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofReq.Unmarshal(m, b)
}
func (m *ProofReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofReq.Marshal(b, m, deterministic)
}
func (m *ProofReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofReq.Merge(m, src)
}
func (m *ProofReq) XXX_Size() int {
	return xxx_messageInfo_ProofReq.Size(m)
}
func (m *ProofReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProofReq proto.InternalMessageInfo

func (m *ProofReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ProofReq) GetAddPieceReq() []*AddpieceReq {
	if m != nil {
		return m.AddPieceReq
	}
	return nil
}

func (m *ProofReq) GetAddPieceRes() []*AddpieceRes {
	if m != nil {
		return m.AddPieceRes
	}
	return nil
}

func (m *ProofReq) GetPostReq() []*PostReq {
	if m != nil {
		return m.PostReq
	}
	return nil
}

func (m *ProofReq) GetPostRes() []*PostRes {
	if m != nil {
		return m.PostRes
	}
	return nil
}

type ProofRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofRes) Reset()         { *m = ProofRes{} }
func (m *ProofRes) String() string { return proto.CompactTextString(m) }
func (*ProofRes) ProtoMessage()    {}
func (*ProofRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_724d63c0ba825e88, []int{1}
}

func (m *ProofRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofRes.Unmarshal(m, b)
}
func (m *ProofRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofRes.Marshal(b, m, deterministic)
}
func (m *ProofRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofRes.Merge(m, src)
}
func (m *ProofRes) XXX_Size() int {
	return xxx_messageInfo_ProofRes.Size(m)
}
func (m *ProofRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofRes.DiscardUnknown(m)
}

var xxx_messageInfo_ProofRes proto.InternalMessageInfo

type AddpieceReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddpieceReq) Reset()         { *m = AddpieceReq{} }
func (m *AddpieceReq) String() string { return proto.CompactTextString(m) }
func (*AddpieceReq) ProtoMessage()    {}
func (*AddpieceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_724d63c0ba825e88, []int{2}
}

func (m *AddpieceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddpieceReq.Unmarshal(m, b)
}
func (m *AddpieceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddpieceReq.Marshal(b, m, deterministic)
}
func (m *AddpieceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddpieceReq.Merge(m, src)
}
func (m *AddpieceReq) XXX_Size() int {
	return xxx_messageInfo_AddpieceReq.Size(m)
}
func (m *AddpieceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddpieceReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddpieceReq proto.InternalMessageInfo

type AddpieceRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddpieceRes) Reset()         { *m = AddpieceRes{} }
func (m *AddpieceRes) String() string { return proto.CompactTextString(m) }
func (*AddpieceRes) ProtoMessage()    {}
func (*AddpieceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_724d63c0ba825e88, []int{3}
}

func (m *AddpieceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddpieceRes.Unmarshal(m, b)
}
func (m *AddpieceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddpieceRes.Marshal(b, m, deterministic)
}
func (m *AddpieceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddpieceRes.Merge(m, src)
}
func (m *AddpieceRes) XXX_Size() int {
	return xxx_messageInfo_AddpieceRes.Size(m)
}
func (m *AddpieceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddpieceRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddpieceRes proto.InternalMessageInfo

type PostReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostReq) Reset()         { *m = PostReq{} }
func (m *PostReq) String() string { return proto.CompactTextString(m) }
func (*PostReq) ProtoMessage()    {}
func (*PostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_724d63c0ba825e88, []int{4}
}

func (m *PostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostReq.Unmarshal(m, b)
}
func (m *PostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostReq.Marshal(b, m, deterministic)
}
func (m *PostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostReq.Merge(m, src)
}
func (m *PostReq) XXX_Size() int {
	return xxx_messageInfo_PostReq.Size(m)
}
func (m *PostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PostReq.DiscardUnknown(m)
}

var xxx_messageInfo_PostReq proto.InternalMessageInfo

type PostRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRes) Reset()         { *m = PostRes{} }
func (m *PostRes) String() string { return proto.CompactTextString(m) }
func (*PostRes) ProtoMessage()    {}
func (*PostRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_724d63c0ba825e88, []int{5}
}

func (m *PostRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRes.Unmarshal(m, b)
}
func (m *PostRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRes.Marshal(b, m, deterministic)
}
func (m *PostRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRes.Merge(m, src)
}
func (m *PostRes) XXX_Size() int {
	return xxx_messageInfo_PostRes.Size(m)
}
func (m *PostRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRes.DiscardUnknown(m)
}

var xxx_messageInfo_PostRes proto.InternalMessageInfo

type ReadPieceReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPieceReq) Reset()         { *m = ReadPieceReq{} }
func (m *ReadPieceReq) String() string { return proto.CompactTextString(m) }
func (*ReadPieceReq) ProtoMessage()    {}
func (*ReadPieceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_724d63c0ba825e88, []int{6}
}

func (m *ReadPieceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPieceReq.Unmarshal(m, b)
}
func (m *ReadPieceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPieceReq.Marshal(b, m, deterministic)
}
func (m *ReadPieceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPieceReq.Merge(m, src)
}
func (m *ReadPieceReq) XXX_Size() int {
	return xxx_messageInfo_ReadPieceReq.Size(m)
}
func (m *ReadPieceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPieceReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPieceReq proto.InternalMessageInfo

type ReadPieceRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPieceRes) Reset()         { *m = ReadPieceRes{} }
func (m *ReadPieceRes) String() string { return proto.CompactTextString(m) }
func (*ReadPieceRes) ProtoMessage()    {}
func (*ReadPieceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_724d63c0ba825e88, []int{7}
}

func (m *ReadPieceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPieceRes.Unmarshal(m, b)
}
func (m *ReadPieceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPieceRes.Marshal(b, m, deterministic)
}
func (m *ReadPieceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPieceRes.Merge(m, src)
}
func (m *ReadPieceRes) XXX_Size() int {
	return xxx_messageInfo_ReadPieceRes.Size(m)
}
func (m *ReadPieceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPieceRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPieceRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProofReq)(nil), "proto.ProofReq")
	proto.RegisterType((*ProofRes)(nil), "proto.ProofRes")
	proto.RegisterType((*AddpieceReq)(nil), "proto.AddpieceReq")
	proto.RegisterType((*AddpieceRes)(nil), "proto.AddpieceRes")
	proto.RegisterType((*PostReq)(nil), "proto.PostReq")
	proto.RegisterType((*PostRes)(nil), "proto.PostRes")
	proto.RegisterType((*ReadPieceReq)(nil), "proto.ReadPieceReq")
	proto.RegisterType((*ReadPieceRes)(nil), "proto.ReadPieceRes")
}

func init() { proto.RegisterFile("fcrpc.proto", fileDescriptor_724d63c0ba825e88) }

var fileDescriptor_724d63c0ba825e88 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x6e, 0xac, 0xd1, 0x66, 0x52, 0x2b, 0x8c, 0x1e, 0x42, 0x4f, 0x65, 0x4f, 0x39, 0xe5, 0x50,
	0x05, 0xcf, 0x05, 0xc1, 0x93, 0x10, 0x56, 0x5f, 0x40, 0x77, 0xa7, 0xb0, 0x20, 0xdd, 0x74, 0x27,
	0xe8, 0xeb, 0xfa, 0x28, 0xe2, 0x76, 0x77, 0x9b, 0x96, 0xf6, 0x94, 0xcc, 0xf7, 0x33, 0xdf, 0x37,
	0x0b, 0xe5, 0x5a, 0xb9, 0x4e, 0x35, 0x9d, 0xb3, 0xbd, 0xc5, 0xdc, 0x7f, 0xc4, 0x6f, 0x06, 0x93,
	0xd6, 0x59, 0xbb, 0x96, 0xb4, 0xc5, 0x7b, 0xc8, 0xdf, 0x4d, 0xff, 0x45, 0x55, 0xb6, 0xc8, 0xea,
	0x42, 0xee, 0x06, 0x7c, 0x84, 0x72, 0xa5, 0x75, 0x6b, 0x48, 0x91, 0xa4, 0x6d, 0x75, 0xb1, 0x18,
	0xd7, 0xe5, 0x12, 0x77, 0x6b, 0x9a, 0x95, 0xd6, 0x5d, 0x60, 0xe4, 0x50, 0x76, 0xe8, 0xe2, 0x6a,
	0x7c, 0xc6, 0xc5, 0x43, 0x17, 0x63, 0x0d, 0xd7, 0xad, 0xe5, 0xfe, 0x3f, 0xe7, 0xd2, 0x3b, 0x66,
	0xc1, 0x11, 0x50, 0x19, 0xe9, 0xbd, 0x92, 0xab, 0xfc, 0x84, 0x92, 0xa3, 0x92, 0x05, 0xa4, 0x0b,
	0x59, 0xdc, 0xf8, 0x56, 0xb1, 0xf1, 0xe1, 0xc8, 0xa2, 0x48, 0xe9, 0xfb, 0x5f, 0x16, 0x33, 0x98,
	0x4a, 0xfa, 0x48, 0x97, 0x1d, 0xcd, 0xbc, 0xfc, 0x81, 0xe9, 0xf3, 0xab, 0xd9, 0xd0, 0x1b, 0xb9,
	0x6f, 0xa3, 0x08, 0x1b, 0x98, 0xbc, 0xd0, 0xc6, 0x47, 0xe2, 0x6d, 0x2c, 0x15, 0x9e, 0x78, 0x7e,
	0x04, 0xb0, 0x18, 0xe1, 0x13, 0x14, 0x69, 0x1f, 0xde, 0x05, 0x7e, 0x98, 0x38, 0x3f, 0x01, 0xb2,
	0x18, 0x7d, 0x5e, 0x79, 0xf4, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x80, 0x73, 0x0f, 0xce, 0xd8,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DMineServiceClient is the client API for DMineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DMineServiceClient interface {
	// request proof
	GenProof(ctx context.Context, in *ProofReq, opts ...grpc.CallOption) (*ProofRes, error)
	ReadPiece(ctx context.Context, in *ReadPieceReq, opts ...grpc.CallOption) (*ReadPieceRes, error)
}

type dMineServiceClient struct {
	cc *grpc.ClientConn
}

func NewDMineServiceClient(cc *grpc.ClientConn) DMineServiceClient {
	return &dMineServiceClient{cc}
}

func (c *dMineServiceClient) GenProof(ctx context.Context, in *ProofReq, opts ...grpc.CallOption) (*ProofRes, error) {
	out := new(ProofRes)
	err := c.cc.Invoke(ctx, "/proto.DMineService/GenProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMineServiceClient) ReadPiece(ctx context.Context, in *ReadPieceReq, opts ...grpc.CallOption) (*ReadPieceRes, error) {
	out := new(ReadPieceRes)
	err := c.cc.Invoke(ctx, "/proto.DMineService/ReadPiece", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DMineServiceServer is the server API for DMineService service.
type DMineServiceServer interface {
	// request proof
	GenProof(context.Context, *ProofReq) (*ProofRes, error)
	ReadPiece(context.Context, *ReadPieceReq) (*ReadPieceRes, error)
}

// UnimplementedDMineServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDMineServiceServer struct {
}

func (*UnimplementedDMineServiceServer) GenProof(ctx context.Context, req *ProofReq) (*ProofRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenProof not implemented")
}
func (*UnimplementedDMineServiceServer) ReadPiece(ctx context.Context, req *ReadPieceReq) (*ReadPieceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPiece not implemented")
}

func RegisterDMineServiceServer(s *grpc.Server, srv DMineServiceServer) {
	s.RegisterService(&_DMineService_serviceDesc, srv)
}

func _DMineService_GenProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProofReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMineServiceServer).GenProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DMineService/GenProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMineServiceServer).GenProof(ctx, req.(*ProofReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMineService_ReadPiece_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPieceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMineServiceServer).ReadPiece(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DMineService/ReadPiece",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMineServiceServer).ReadPiece(ctx, req.(*ReadPieceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DMineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DMineService",
	HandlerType: (*DMineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenProof",
			Handler:    _DMineService_GenProof_Handler,
		},
		{
			MethodName: "ReadPiece",
			Handler:    _DMineService_ReadPiece_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fcrpc.proto",
}
